language: java

jdk:
 - oraclejdk7
 - openjdk7
 - oraclejdk8

matrix:
 allow_failures:
   - openjdk7
   - oraclejdk8

notifications:
  email: false

install:
 - redis-server > /dev/null 2>&1 &
 - cd ..
 - git clone --depth 1 https://github.com/Qabel/qabel.git
 - cd qabel
 - git submodule init
 - git submodule update --depth 1
 - rm -rf qabel-core
 - mv ../qabel-core ./
 - virtualenv --system-site-packages qabel-drop
 - source qabel-drop/bin/activate 
 - pip install --upgrade pip
 - pip install --user -r qabel-drop/requirements.txt

cache:
 apt: true
 directories:
  - $HOME/.cache/pip
  - $HOME/.gradle/caches
  - $HOME/build/qabel/qabel-drop/lib

sudo: false

addons:
 apt:
  packages:
   - python-pip
   - nodejs
   - python-virtualenv

script:
 - travis_wait ./gradlew check
